        edit TB_ORDER
        
         edit TB_ORDER_DE 
         
          edit TB_DELIVERY 
        
         edit TB_PURCHASE 
         
         CREATE SEQUENCE SEQ_FAQ_NO

CREATE SEQUENCE SEQ_POINT_NO

-- 포인트타입 컬럼이 ERD에는 있는데 오라클에 없어서 추가함
alter table tb_point add point_type number(20)

-- 회원포인트는 컬럼 없이 sum으로
ALTER TABLE tb_point DROP column member_point
]
edit 

edit TB_ADMIN 

edit  TB_MEMBER 
 MEMBER_NO         NUMBER(20)                  NOT NULL,
  MEMBER_ADDRESS    VARCHAR2(500 BYTE),
  MEMBER_NAME       VARCHAR2(30 BYTE)           NOT NULL,
  MEMBER_PHONE      NUMBER(30),
  MEMBER_ZIPCODE    NUMBER(20),
  MEMBER_EMAIL      VARCHAR2(50 BYTE)           NOT NULL,

 edit   TB_CART
    CART_NO        VARCHAR2(100 BYTE)             NOT NULL,
  MEMBER_NO      NUMBER(20)                     NOT NULL,
  MD_NO          NUMBER(20)                     NOT NULL,
  CART_QUANTITY  NUMBER(5)                      NOT NULL,
  ORDER_TYPE     VARCHAR2(20 BYTE)              NOT NULL

edit  TB_ORDER 
 ORDER_NO          VARCHAR2(100 BYTE)          NOT NULL,
  MEMBER_NO         NUMBER(20)                  NOT NULL,
  CART_NO           VARCHAR2(100 BYTE)          NOT NULL,
  ORDER_PAYMENT     NUMBER(20)                  NOT NULL,
  ORDER_DATE        VARCHAR2(200 BYTE)          NOT NULL,
  ORDER_AMOUNT      NUMBER(20)                  NOT NULL,
  ORDER_USED_POINT  NUMBER(20)
  
edit  TB_ORDER_DE 
   ORDER_DE_NO        VARCHAR2(100 BYTE)         NOT NULL,
  ORDER_NO           VARCHAR2(100 BYTE)         NOT NULL,
  ORDER_DE_QUANTITY  NUMBER(5)                  DEFAULT 0                     NOT NULL,
  ORDER_DE_PRICE     NUMBER(20)                 NOT NULL,
  ORDER_DE_CANCEL    VARCHAR2(100 BYTE)         DEFAULT 'N'

edit TB_MD 

edit  TB_AMD 
 MD_NO                NUMBER(20)               NOT NULL,
  MD_PRICE             NUMBER(10)               NOT NULL,
  MD_IMAGE             VARCHAR2(100 BYTE)       NOT NULL,
  MD_NAME              VARCHAR2(100 BYTE)       NOT NULL,
  MD_BRAND             VARCHAR2(100 BYTE)       NOT NULL,
  MD_IMAGE_URL         VARCHAR2(4000 BYTE),
  
edit    TB_DELIVERY 
  DELIVERY_STATUS   VARCHAR2(100 BYTE)          NOT NULL,
  ORDER_NO          VARCHAR2(100 BYTE)          NOT NULL,
  DELIVERY_DATE     VARCHAR2(100 BYTE),
  DELIVERY_FEE      VARCHAR2(100 BYTE),
  DELIVERY_NO       VARCHAR2(100 BYTE),
  DELIVERY_COMPANY  VARCHAR2(100 BYTE)
  
TB_PURCHASE 
  PURCHASE_NO      VARCHAR2(100 BYTE)           NOT NULL,
  ORDER_NO         VARCHAR2(100 BYTE)           NOT NULL,
  PURCHASE_METHOD  VARCHAR2(50 BYTE)            NOT NULL
  
  

select  TB_ORDER.ORDER_NO, TB_ORDER.MEMBER_NO, TB_ORDER.CART_NO
, TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE, TB_ORDER.ORDER_AMOUNT
, TB_ORDER.ORDER_USED_POINT
, TB_ORDER_DE.ORDER_DE_NO, TB_ORDER_DE.ORDER_DE_QUANTITY, TB_ORDER_DE.ORDER_DE_PRICE, TB_ORDER_DE.ORDER_DE_CANCEL
from TB_ORDER full outer join TB_ORDER_DE 
on TB_ORDER.ORDER_NO = TB_ORDER_DE.ORDER_NO
where TB_ORDER.ORDER_NO = TB_ORDER_DE.ORDER_NO

select  TB_ORDER.ORDER_NO, TB_ORDER.MEMBER_NO, TB_ORDER.CART_NO
, TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE, TB_ORDER.ORDER_AMOUNT
, TB_ORDER.ORDER_USED_POINT
, TB_ORDER_DE.ORDER_DE_NO, TB_ORDER_DE.ORDER_DE_QUANTITY, TB_ORDER_DE.ORDER_DE_PRICE, TB_ORDER_DE.ORDER_DE_CANCEL
from TB_ORDER full outer join TB_ORDER_DE 
on TB_ORDER.ORDER_NO = TB_ORDER_DE.ORDER_NO
where TB_ORDER.ORDER_NO = TB_ORDER_DE.ORDER_NO


select TB_ORDER.ORDER_NO, TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE
        , TB_ORDER.ORDER_USED_POINT
        , TB_ORDER_DE.ORDER_DE_CANCEL
        , TB_DELIVERY.DELIVERY_STATUS, TB_DELIVERY.DELIVERY_DATE
        , TB_DELIVERY.DELIVERY_COMPANY, TB_DELIVERY.DELIVERY_NO
        , TB_DELIVERY.DELIVERY_FEE, TB_DELIVERY.DELIVERY_ADDRESS
        , TB_DELIVERY.DELIVERY_PHONE
        , TB_PURCHASE.PURCHASE_METHOD
from TB_ORDER
inner join TB_ORDER_DE
    on TB_ORDER.ORDER_NO = TB_ORDER_DE.ORDER_NO
inner join TB_DELIVERY
    on TB_ORDER_DE.ORDER_NO = TB_DELIVERY.ORDER_NO
inner join TB_PURCHASE
    on TB_ORDER.ORDER_NO = TB_PURCHASE.ORDER_NO
where TB_ORDER.ORDER_NO = 'o_1667639724623'


select TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE
    , TB_ORDER.ORDER_USED_POINT
    , TB_MEMBER.MEMBER_NAME
    , TB_CART.MD_NO, TB_CART.CART_QUANTITY
    , TB_CART.ORDER_TYPE
    , TB_MD.MD_PRICE, TB_MD.MD_IMAGE
    , TB_MD.MD_NAME, TB_MD.MD_BRAND
    , TB_MD.MD_IMAGE_URL
from TB_ORDER
inner join TB_MEMBER 
on TB_ORDER.MEMBER_NO = TB_MEMBER.MEMBER_NO
inner join TB_CART
on TB_MEMBER.MEMBER_NO = TB_CART.MEMBER_NO
inner join TB_MD 
on TB_MD.MD_NO = TB_CART.MD_NO
where ORDER_NO = 'o_1667639724623'


    select TB_ORDER.ORDER_NO, TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE
            , TB_ORDER.ORDER_USED_POINT, TB_ORDER_DE.ORDER_DE_CANCEL
            , TB_DELIVERY.DELIVERY_STATUS, TB_DELIVERY.DELIVERY_DATE, TB_DELIVERY.DELIVERY_COMPANY
            , TB_DELIVERY.DELIVERY_NO, TB_DELIVERY.DELIVERY_FEE, TB_DELIVERY.DELIVERY_ADDRESS
            , TB_DELIVERY.DELIVERY_PHONE
            , TB_PURCHASE.PURCHASE_METHOD
        from TB_ORDER
            inner join TB_ORDER_DE
                on TB_ORDER.ORDER_NO = TB_ORDER_DE.ORDER_NO
            inner join TB_DELIVERY
                on TB_ORDER_DE.ORDER_NO = TB_DELIVERY.ORDER_NO
            inner join TB_PURCHASE
                on TB_ORDER.ORDER_NO = TB_PURCHASE.ORDER_NO

select TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE, TB_ORDER.ORDER_USED_POINT
            , TB_MEMBER.MEMBER_NAME
            , TB_CART.MD_NO, TB_CART.CART_QUANTITY, TB_CART.ORDER_TYPE
            , TB_MD.MD_PRICE, TB_MD.MD_IMAGE, TB_MD.MD_NAME, TB_MD.MD_BRAND, TB_MD.MD_IMAGE_URL
        from TB_ORDER
            inner join TB_MEMBER
                on TB_ORDER.MEMBER_NO = TB_MEMBER.MEMBER_NO
            inner join TB_CART
                on TB_MEMBER.MEMBER_NO = TB_CART.MEMBER_NO
            inner join TB_MD
                on TB_MD.MD_NO = TB_CART.MD_NO

ALTER TABLE TB_DELIVERY ADD DELIVERY_ADDRESS VARCHAR(4000);

ALTER TABLE TB_DELIVERY ADD DELIVERY_PHONE VARCHAR(4000);

ALTER TABLE TB_DELIVERY  DROP PRIMARY KEY

ALTER TABLE TB_DELIVERY DROP CONSTRAINT FK_TB_ORDER_TO_TB_DELIVERY_1