edit TB_POINT 
edit TB_ORDER 
edit TB_DELIVERY 
edit TB_CART  
edit TB_MD  
edit TB_ORDER_DE 
edit TB_SUBS  
edit TB_STORE 

update 

UPDATE TB_POINT SET POINT_USED_SAVED = '미등록' WHERE Phone is null


UPDATE
    TB_POINT
SET
    TB_POINT.POINT_USED_SAVED = (TB_POINT.POINT_USED_SAVED-TB_ORDER.ORDER_USED_POINT)
FROM
    TB_POINT
INNER JOIN
    TB_ORDER
ON 
    TB_POINT.MEMBER_NO= 2;
    
    
MERGE INTO TB_POINT
USING (SELECT TB_ORDER.ORDER_NO,  TB_ORDER.ORDER_USED_POINT, TB_POINT.MEMBER_NO,POINT_USED_SAVED FROM TB_ORDER INNER JOIN TB_POINT ON TB_POINT.MEMBER_NO = TB_ORDER.MEMBER_NO WHERE TB_POINT.MEMBER_NO=2 AND TB_ORDER.ORDER_NO = 'O_1667974262721') TB_ORDER
ON (TB_POINT.MEMBER_NO= 2)
WHEN MATCHED THEN UPDATE SET TB_POINT.POINT_USED_SAVED = (TB_ORDER.POINT_USED_SAVED-TB_ORDER.ORDER_USED_POINT);



SELECT TB_ORDER.ORDER_NO,  TB_ORDER.ORDER_USED_POINT, TB_POINT.MEMBER_NO,POINT_USED_SAVED  FROM TB_ORDER INNER JOIN TB_POINT 
ON TB_POINT.MEMBER_NO = TB_ORDER.MEMBER_NO 
WHERE TB_POINT.MEMBER_NO=2
AND TB_ORDER.ORDER_NO = 'O_1667974262721';


 INSERT ALL
 INTO TB_ORDER (ORDER_NO, MEMBER_NO, CART_NO, ORDER_PAYMENT
        , ORDER_DATE, ORDER_AMOUNT, ORDER_USED_POINT)
        VALUES(#{ORDER_NO}, #{MEMBER_NO},#{CART_NO}, #{ORDER_PAYMENT}
        ,to_char(sysdate, 'YYYY-MM-DD HH24:MI:SS'), #{ORDER_AMOUNT}, #{ORDER_USED_POINT})TB_SUBS 
        INTO TB_PURCHASE (PURCHASE_NO, ORDER_NO, PURCHASE_METHOD)
        VALUES(#{PURCHASE_NO}, #{ORDER_NO}, #{PURCHASE_METHOD})
         INTO TB_ORDER_DE   (ORDER_DE_NO, ORDER_NO, ORDER_DE_QUANTITY
         ,ORDER_DE_PRICE,ORDER_DE_CANCEL)
        VALUES(#{ORDER_DE_NO}, #{ORDER_NO}, #{ORDER_DE_QUANTITY}
        , #{ORDER_DE_PRICE}, #{ORDER_DE_CANCEL})
         INTO TB_DELIVERY  (DELIVERY_STATUS, ORDER_NO, DELIVERY_ADDRESS, DELIVERY_PHONE)
        VALUES(#{DELIVERY_STATUS}, #{ORDER_NO}, #{DELIVERY_ADDRESS}, #{DELIVERY_PHONE}) 
         INTO TB_SUBS  (SUB_NO)
        VALUES(#{SUB_NO}) 
        SELECT * FROM DUAL 
        
        
        
        SELECT car.member_no, car.cart_no, car.order_type, car.cart_quantity
             , md.md_name, md.md_brand, md.md_price, md.md_image_url,md.md_discount, md.md_no
      FROM tb_cart car, tb_md md
      WHERE car.md_no = md.md_no
      AND car.order_type = 'T'
      AND car.member_no = 2
      
      CREATE SEQUENCE board_no_seq
      CREATE SEQUENCE CART_SEQ
      CART_SEQ
      
      
      select TB_ORDER.ORDER_NO,TB_ORDER.ORDER_PAYMENT, TB_ORDER.ORDER_DATE
            , TB_ORDER.ORDER_USED_POINT,TB_ORDER.CART_NO
            , TB_MEMBER.MEMBER_NAME
            , TB_CART.MD_NO, TB_CART.CART_QUANTITY, TB_CART.ORDER_TYPE
            , TB_MD.MD_PRICE, TB_MD.MD_IMAGE, TB_MD.MD_NAME, TB_MD.MD_BRAND, TB_MD.MD_IMAGE_URL
        from TB_ORDER
            inner join TB_MEMBER
                on TB_ORDER.MEMBER_NO = TB_MEMBER.MEMBER_NO
            inner join TB_CART
                on TB_ORDER.CART_NO = TB_CART.CART_NO
            inner join TB_MD
                on TB_MD.MD_NO = TB_CART.MD_NO
                
                
MERGE INTO 
(select TB_ORDER_DE.ORDER_NO ORDER_NO, TB_ORDER_DE.ORDER_DE_CANCEL ORDER_DE_CANCEL, TB_DELIVERY.DELIVERY_STATUS DELIVERY_STATUS
from TB_ORDER_DE inner join TB_DELIVERY  
on TB_ORDER_DE.ORDER_NO =TB_DELIVERY.ORDER_NO 
WHERE TB_ORDER_DE.ORDER_NO ='o_1667842995541') A
USING TB_DELIVERY B
ON ( A.ORDER_NO = B.ORDER_NO )
WHERE MATCHED THEN UPDATE SET A.ORDER_DE_CANCEL= '주문취소', A.DELIVERY_STATUS='Y';


MERGE INTO TB_POINT
USING (SELECT TB_ORDER.ORDER_NO,  TB_ORDER.ORDER_USED_POINT, TB_POINT.MEMBER_NO,POINT_USED_SAVED FROM TB_ORDER INNER JOIN TB_POINT ON TB_POINT.MEMBER_NO = TB_ORDER.MEMBER_NO WHERE TB_POINT.MEMBER_NO=2 AND TB_ORDER.ORDER_NO = 'O_1667974262721') TB_ORDER
ON (TB_POINT.MEMBER_NO= 2)
WHEN MATCHED THEN UPDATE SET TB_POINT.POINT_USED_SAVED = (TB_ORDER.POINT_USED_SAVED-TB_ORDER.ORDER_USED_POINT);


select * from TB_ORDER_DE inner join TB_DELIVERY  on TB_ORDER_DE.ORDER_NO =TB_DELIVERY.ORDER_NO where TB_ORDER_DE.ORDER_NO ='T_1667971421623'

update TB_ORDER_DE
set ORDER_DE_CANCEL= 'Y'
WHERE ORDER_NO ='T_1667971421623'

update TB_DELIVERY
set DELIVERY_STATUS= '주문취소'
WHERE ORDER_NO ='T_1667971421623'