ALTER TABLE tb_community
MODIFY board_report_count DEFAULT 0

commit

edit TB_STORE 

edit TB_AMD 

edit TB_ASTOCK 


update (SELECT A.STUDNET_NAME, B.STUDNET_NAMEFROM CLASS A 
INNER JOIN STUDENT B
ON A.STUDENT_ID = B.STUDENT_ID
WHERE A.STUDENT_ID = '20150161')
SET A.STUDNET_NAME = 'ȫ�浿',B.STUDNET_NAME = 'ȫ�浿',

UPDATE   --/*+bypass_ujvc*/
(SELECT TB_AMD.MD_NO, TB_AMD.MD_CONTENT, TB_AMD.MD_PRICE, TB_AMD.MD_IMAGE, TB_AMD.MD_DETAIL_IMAGE
        ,TB_AMD.MD_COST, TB_AMD.MD_CATEGORY, TB_AMD.MD_DISCOUNT, TB_AMD.MD_NAME, TB_AMD.MD_BRAND, TB_AMD.STORE_NO
        ,TB_AMD.MD_IMAGE_URL, TB_AMD.MD_DETAIL_IMAGE_URL, TB_ASTOCK.MD_NO, TB_ASTOCK.ST_AMOUNT
        FROM TB_AMD LEFT JOIN TB_ASTOCK
        ON TB_AMD.MD_NO = TB_ASTOCK.MD_NO)
SET     TB_AMD.MD_CONTENT = '1029'
        ,TB_AMD.MD_PRICE = 30
        ,TB_AMD.MD_NAME = '1029'
        ,TB_AMD.MD_IMAGE = '1029'
        ,TB_AMD.MD_IMAGE_URL = '1029'
        ,TB_AMD.MD_COST = 30
        ,TB_AMD.MD_CATEGORY = '1029'
        ,TB_AMD.MD_DISCOUNT = 30}
        ,TB_AMD.MD_BRAND = '1029'
        ,TB_AMD.STORE_NO = 30
        ,TB_AMD.MD_DETAIL_IMAGE='1029'
        ,TB_AMD.MD_DETAIL_IMAGE_URL='1029'
        ,TB_ASTOCK.ST_AMOUNT='30'
WHERE TB_AMD.MD_NO = 20
        
        
        SELECT TB_AMD.MD_NO,MD_CONTENT,MD_PRICE,MD_IMAGE,MD_DETAIL_IMAGE
        ,MD_COST,MD_CATEGORY,MD_DISCOUNT,MD_NAME,MD_BRAND,STORE_NO,MD_IMAGE_URL,MD_DETAIL_IMAGE_URL,TB_ASTOCK.ST_AMOUNT
        FROM TB_AMD LEFT JOIN TB_ASTOCK
        ON TB_AMD.MD_NO = TB_ASTOCK.MD_NO
        WHERE TB_AMD.MD_NO = 7
        
        
        
        UPDATE TB_AMD

   SET PHONE = (

   SELECT PHONE

                FROM KIM_IMS_PERSON B

                WHERE B.PER_ID = A.PER_ID

               );
               
               
             TB_AMD 
             
             
             
             SELECT TB_AMD.MD_NO,MD_CONTENT,MD_PRICE,MD_IMAGE,MD_DETAIL_IMAGE
        ,MD_COST,MD_CATEGORY,MD_DISCOUNT,MD_NAME,MD_BRAND,STORE_NO
        ,MD_IMAGE_URL,MD_DETAIL_IMAGE_URL,ST_AMOUNT
        FROM TB_AMD 

