
-문제1
--영화 티켓을 받을 수 있는 사람의 명단과 현재 가지고 있는 포인트, 영화 티켓의 포인트
--그리고 그 티켓을 사용한 후 남은 예상 포인트를 출력하시오.
SELECT T_GIFTMEM.NAME_VC 이름, T_GIFTMEM.POINT_NU 보유
,T_GIFTPOINT.POINT_NU 적용, (T_GIFTMEM.POINT_NU-T_GIFTPOINT.POINT_NU) "남은 예상"
FROM T_GIFTMEM,T_GIFTPOINT
WHERE T_GIFTPOINT.NAME_VC = '영화티켓'
AND T_GIFTMEM.POINT_NU-T_GIFTPOINT.POINT_NU >0
--문제2
--김유신씨가 보유하고 있는 마일리지 포인트로 얻을 수 있는 상품 중 가장 포인트가 높은 것은 무엇인가?
SELECT MAX(T_GIFTPOINT.NAME_VC) NAME_VC ,MAX(T_GIFTPOINT.POINT_NU) POINT_NU
FROM T_GIFTMEM,T_GIFTPOINT
WHERE T_GIFTMEM.NAME_VC = '김유신'
AND T_GIFTPOINT.POINT_NU<T_GIFTMEM.POINT_NU

SELECT NAME_VC,POINT_NU
FROM
(SELECT T_GIFTPOINT.NAME_VC NAME_VC,T_GIFTPOINT.POINT_NU POINT_NU
FROM T_GIFTMEM,T_GIFTPOINT
WHERE T_GIFTMEM.NAME_VC = '김유신'
AND T_GIFTPOINT.POINT_NU<T_GIFTMEM.POINT_NU
ORDER BY T_GIFTPOINT.POINT_NU DESC)
WHERE rownum<2
