

SELECT T.CDATE,T.AMT,C.CRATE, TO_CHAR((T.AMT*C.CRATE),'999,999,999,999')||'원' 한화금액
       FROM (SELECT ROWNUM R1,CRATE
             FROM TEST02
             WHERE CDATE BETWEEN '20010901' AND '20010910') C
             , (SELECT ROWNUM R2, CDATE,AMT
             FROM TEST02
             WHERE CDATE BETWEEN '20010903' AND '20010911') T
       WHERE C.R1 = T.R2

SELECT ROWNUM RNO,C1.BIRTH_DATE ID1, C1.EMP_NAME NAME1
      ,C2.BIRTH_DATE ID2, C2.EMP_NAME NAME2
      ,C3.BIRTH_DATE ID3, C3.EMP_NAME NAME3
      ,C4.BIRTH_DATE ID4, C4.EMP_NAME NAME4
      ,C0.BIRTH_DATE ID5, C0.EMP_NAME NAME5
FROM( SELECT CEIL(NO/5) RNO
      ,MOD(NO,5) CNO
      ,NO
      ,EMP_NAME,BIRTH_DATE
  FROM (
        SELECT ROWNUM NO
              ,EMP_NAME,BIRTH_DATE
          FROM TEMP
       )
       WHERE MOD(NO,5) = 1) C1
       ,( SELECT CEIL(NO/5) RNO
      ,MOD(NO,5) CNO
      ,NO
      ,EMP_NAME,BIRTH_DATE
  FROM (
        SELECT ROWNUM NO
              ,EMP_NAME,BIRTH_DATE
          FROM TEMP
       )
       WHERE MOD(NO,5) = 2) C2
       ,( SELECT CEIL(NO/5) RNO
      ,MOD(NO,5) CNO
      ,NO
      ,EMP_NAME,BIRTH_DATE
  FROM (
        SELECT ROWNUM NO
              ,EMP_NAME,BIRTH_DATE
          FROM TEMP
       )
       WHERE MOD(NO,5) = 3) C3
       ,( SELECT CEIL(NO/5) RNO
      ,MOD(NO,5) CNO
      ,NO
      ,EMP_NAME,BIRTH_DATE
  FROM (
        SELECT ROWNUM NO
              ,EMP_NAME,BIRTH_DATE
          FROM TEMP
       )
       WHERE MOD(NO,5) = 4) C4
       ,( SELECT CEIL(NO/5) RNO
      ,MOD(NO,5) CNO
      ,NO
      ,EMP_NAME,BIRTH_DATE
  FROM (
        SELECT ROWNUM NO
              ,EMP_NAME,BIRTH_DATE
          FROM TEMP
       )
       WHERE MOD(NO,5) = 0) C0
       WHERE C1.RNO = C2.RNO AND C1.RNO = C3.RNO AND C1.RNO = C3.RNO AND C1.RNO = C4.RNO AND C1.RNO = C0.RNO
          SELECT CEIL(ROWNUM/5) RNO
      ,MAX(DECODE(MOD(ROWNUM,5),1,BIRTH_DATE)) ID1
      ,MAX(DECODE(MOD(ROWNUM,5),1,EMP_NAME)) NAME1
      ,MAX(DECODE(MOD(ROWNUM,5),2,BIRTH_DATE)) ID2
      ,MAX(DECODE(MOD(ROWNUM,5),2,EMP_NAME)) NAME2
            ,MAX(DECODE(MOD(ROWNUM,5),3,BIRTH_DATE)) ID3
      ,MAX(DECODE(MOD(ROWNUM,5),3,EMP_NAME)) NAME3
      ,MAX(DECODE(MOD(ROWNUM,5),4,BIRTH_DATE)) ID4
      ,MAX(DECODE(MOD(ROWNUM,5),4,EMP_NAME)) NAME4
      ,MAX(DECODE(MOD(ROWNUM,5),0,BIRTH_DATE)) ID5
      ,MAX(DECODE(MOD(ROWNUM,5),0,EMP_NAME)) NAME5
  FROM (
        SELECT ROWNUM
               ,BIRTH_DATE
              ,EMP_NAME
          FROM TEMP)
          GROUP BY CEIL(ROWNUM/5)
