
SELECT INDATE_VC 판매날짜, SUM(QTY_NU)||'개' 판매갯수, SUM(QTY_NU*PRICE_NU)||'원' 판매가격
FROM T_ORDERBASKET
GROUP BY INDATE_VC
UNION ALL
SELECT NVL2(A.판매날짜,'총계',NULL) 판매날짜,SUM(A.판매갯수)||'개' 판매갯수, SUM(A.판매가격)||'원' 판매가격
FROM( SELECT INDATE_VC 판매날짜, SUM(QTY_NU) 판매갯수, SUM(QTY_NU*PRICE_NU) 판매가격
FROM T_ORDERBASKET
GROUP BY INDATE_VC) A
GROUP BY NVL2(A.판매날짜,'총계',NULL)


SELECT INDATE_VC 판매날짜, SUM(QTY_NU)||'개' 판매갯수, SUM(QTY_NU*PRICE_NU)||'원' 판매가격
FROM T_ORDERBASKET
GROUP BY INDATE_VC
UNION ALL
SELECT NVL2(COUNT(INDATE_VC),'총계',NULL) 판매날짜,SUM(QTY_NU)||'개' 판매갯수, SUM(QTY_NU*PRICE_NU)||'원' 판매가격 --판매날짜는 어차피 치환할거라 카운트 씀
FROM T_ORDERBASKET


SELECT DECODE(INDATE_VC,NULL,'총계',INDATE_VC) 판매날짜
,SUM(QTY_NU)||'개' 판매갯수,SUM(QTY_NU*PRICE_NU)||'원' 판매가격
FROM T_ORDERBASKET
GROUP BY ROLLUP (INDATE_VC)
