edit TB_STORE 

select * from TB_STORE 



edit TB_AMD

UPDATE TB_STORE
SET 

    SELECT STORE_NO, MD_NO, STORE_CONTACT, STORE_MANAGER, STORE_MEMO,STORE_YN,STORE_START_DATE,FIELD
        FROM tb_store
      
        ORDER BY STORE_NO asc   
        
        
        INSERT INTO TB_STORE (STORE_NO, MD_NO, STORE_CONTACT, STORE_MANAGER, STORE_MEMO,STORE_YN,FIELD,STORE_START_DATE) 
       VALUES(rowCount + 1,1,010-8888-8888,±èÆÈÆÈ,ÆÈ°³¾¿,'Y',ÆÈÆÈ´À³¦,to_char(sysdate, 'YYYY-MM-DD'))
       
edit TB_STORE

EDIT TB_AMD  

CREATE SEQUENCE STORE_NO_SEQ



SELECT TB_AMD.MD_NO,TB_AMD.MD_NAME,STORE_CONTACT,STORE_MANAGER,STORE_MEMO,STORE_YN,STORE_START_DATE,FIELD,TB_STORE.STORE_NO
FROM (SELECT STORE_NO,MD_BRAND,MD_NO,MD_NAME FROM TB_AMD WHERE STORE_NO=1) TB_AMD, 
(SELECT STORE_NO,STORE_CONTACT,STORE_MANAGER,STORE_MEMO,STORE_YN,STORE_START_DATE,FIELD FROM TB_STORE WHERE STORE_NO=1) TB_STORE

SELECT STORE_NO,STORE_CONTACT,STORE_MANAGER,STORE_MEMO,STORE_YN,STORE_START_DATE,FIELD,TB_AMD.MD_NO,TB_AMD.MD_BRAND

        FROM TB_STORE LEFT OUTER JOIN TB_AMD
        
        
        
SELECT DISTINCT TB_STORE.STORE_NO,MD_NO,MD_NAME,STORE_CONTACT,STORE_MANAGER,STORE_MEMO,STORE_YN,STORE_START_DATE,FIELD

FROM TB_STORE LEFT JOIN TB_AMD
ON TB_STORE.STORE_NO = TB_AMD.STORE_NO
WHERE TB_AMD.STORE_NO =1 
 GROUP BY TB_STORE.STORE_NO
 
 
 
 SELECT DISTINCT TB_STORE.STORE_NO,STORE_CONTACT,STORE_MANAGER,STORE_MEMO,STORE_YN,STORE_START_DATE,FIELD

FROM TB_STORE LEFT JOIN TB_AMD
ON TB_STORE.STORE_NO = TB_AMD.STORE_NO

 GROUP BY TB_STORE.STORE_NO


 
;
